#General
NAME = "CTS"
USER_MANAGEMENT="Quản lý nhân viên"
#Mission avaiable
AVAIABLE_MISSIONSYSTEM = "NHIỆM VỤ ĐANG CÓ TRÊN HỆ THỐNG"
CHOICE_MISSION = "Lựa chọn nhiệm vụ"
YOUR_MISSION ="Nhiệm vụ của bạn"
MISSIONSYSTEM ="Nhiệm vụ trên hệ thống"
AVAIABLE_MISSION = "Nhiệm vụ đang có"
MISSION_DETAIL = "Chi Tiết Nhiệm Vụ"
MISSION_LIST = "Danh Sách Nhiệm Vụ"
#Table AvaiableMission constants
ID="ID"
NAME_MISSION = "Tên Nhiệm Vụ"
START_DATE ="Ngày Bắt Đầu"
END_DATE = "Ngày Kết Thúc"
POINT = "Điểm"
QUANTITY_REMAINING ="Số Lượng Còn"
STATUS ="Trạng Thái"
ACTION ="Tác Vụ"
DESCRIPTION = "Mô Tả"
TIME_REMAINING ="Ngày Kết Thúc"
STT = "STT"
#Notification
AVAIABLE = "Còn"
UNAVAIABLE ="Không"
NOTIFICATION ="Thông Báo"
CANCEL ="Hủy"
DOING ="Đang Làm"
COMPLETE ="Hoàn Thành"
BACK_SIDE ="Quay lại trang trước"
DAY = "Ngày"
CLOSE ="Đóng"
#Mission Search
MISSION_LIST_OF = "Danh Sách Nhiệm Vụ Của"
#User Mission
YOUR_MISSION_BOL = "NHIỆM VỤ CỦA BẠN"
